export type FilmType = "color" | "bw";
export type FilmProcess = "c41" | "bw" | "e6";

/**
 * Everything here was 35mm until Polaroid was added. Format is a hard divide, not a
 * filter: instant film has no ISO worth comparing, is sold by camera compatibility
 * rather than by roll, and is priced per shot — so it gets its own page rather than
 * a row in a list of 35mm stock.
 */
export type FilmFormat = "35mm" | "instant";

export type FilmSeed = {
  id: string;
  brand: string;
  name: string;
  iso: number | null;
  type: FilmType;
  process: FilmProcess | null;
  aliases: string[];
  /**
   * Exposure count to assume when a listing's title doesn't state one. Only set it
   * for films sold in a single length — CineStill, for example, has no 24-exposure
   * roll — otherwise a guess would put a listing under the wrong variant filter.
   * Never applied to bulk rolls, which have no exposure count.
   */
  defaultExposures?: 8 | 16 | 24 | 36;
  /**
   * Pack size to assume when a listing's title doesn't state one. For products only
   * ever sold as a fixed bundle, where no title says "3 pack".
   */
  defaultPackSize?: number;
  /**
   * `core` (the default) is the curated set the site shows first and every store
   * scrapes. `extended` is everything else: still tracked, but shown only when the
   * reader asks for it, and skipped by the browser-driven stores, which load a page
   * per film at roughly 12 seconds each and would otherwise take hours.
   *
   * Films found by `npm run discover` should be added as `extended` unless they are
   * genuinely common.
   */
  tier?: "core" | "extended";
  /**
   * Defaults to `35mm`. Instant film is matched by a different title test, skipped by
   * the browser-driven stores, and shown on its own page — see `FilmFormat`.
   */
  format?: FilmFormat;
};

/** Films default to `core`, matching the catalogue before tiers existed. */
export function filmTier(f: Pick<FilmSeed, "tier">): "core" | "extended" {
  return f.tier ?? "core";
}

/** Films default to 35mm, matching the catalogue before instant film was added. */
export function filmFormat(f: Pick<FilmSeed, "format">): FilmFormat {
  return f.format ?? "35mm";
}

export const filmSeeds: FilmSeed[] = [
  {
    id: "kodak-portra-160",
    brand: "Kodak",
    name: "Portra 160",
    iso: 160,
    type: "color",
    process: "c41",
    aliases: ["portra 160", "kodak portra 160", "portra160"],
  },
  {
    id: "kodak-portra-400",
    brand: "Kodak",
    name: "Portra 400",
    iso: 400,
    type: "color",
    process: "c41",
    aliases: ["portra 400", "kodak portra 400", "portra400"],
  },
  {
    id: "kodak-portra-800",
    brand: "Kodak",
    name: "Portra 800",
    iso: 800,
    type: "color",
    process: "c41",
    aliases: ["portra 800", "kodak portra 800", "portra800"],
  },
  {
    id: "kodak-ektar-100",
    brand: "Kodak",
    name: "Ektar 100",
    iso: 100,
    type: "color",
    process: "c41",
    aliases: ["ektar 100", "kodak ektar 100", "ektar100", "ektar"],
  },
  {
    id: "kodak-colorplus-200",
    brand: "Kodak",
    name: "ColorPlus 200",
    iso: 200,
    type: "color",
    process: "c41",
    aliases: ["colorplus 200", "kodak colorplus 200", "color plus 200", "colorplus200", "colorplus"],
  },
  {
    id: "kodak-gold-200",
    brand: "Kodak",
    name: "Gold 200",
    iso: 200,
    type: "color",
    process: "c41",
    aliases: ["gold 200", "kodak gold 200", "kodak gold200"],
  },
  {
    id: "kodak-ultramax-400",
    brand: "Kodak",
    name: "Ultramax 400",
    iso: 400,
    type: "color",
    process: "c41",
    aliases: ["ultramax 400", "kodak ultramax 400", "ultramax400"],
  },
  {
    id: "kodak-ektacolor-160",
    brand: "Kodak",
    name: "Ektacolor 160",
    iso: 160,
    type: "color",
    process: "c41",
    aliases: [
      "ektacolor 160",
      "kodak ektacolor 160",
      "ektacolor160",
      "ektacolor pro 160",
      "kodak ektacolor pro 160",
    ],
  },
  {
    id: "kodak-ektacolor-400",
    brand: "Kodak",
    name: "Ektacolor 400",
    iso: 400,
    type: "color",
    process: "c41",
    aliases: [
      "ektacolor 400",
      "kodak ektacolor 400",
      "ektacolor400",
      "ektacolor pro 400",
      "kodak ektacolor pro 400",
    ],
  },
  {
    id: "kodak-ektacolor-800",
    brand: "Kodak",
    name: "Ektacolor 800",
    iso: 800,
    type: "color",
    process: "c41",
    aliases: [
      "ektacolor 800",
      "kodak ektacolor 800",
      "ektacolor800",
      "ektacolor pro 800",
      "kodak ektacolor pro 800",
    ],
  },
  {
    id: "kodak-tri-x-400",
    brand: "Kodak",
    name: "Tri-X 400",
    iso: 400,
    type: "bw",
    process: "bw",
    aliases: ["tri-x 400", "trix 400", "kodak tri-x", "kodak tri-x 400"],
  },
  {
    id: "kodak-t-max-100",
    brand: "Kodak",
    name: "T-MAX 100",
    iso: 100,
    type: "bw",
    process: "bw",
    aliases: ["t-max 100", "tmax 100", "kodak t-max 100", "kodak tmax 100", "tmax100"],
  },
  {
    id: "kodak-t-max-400",
    brand: "Kodak",
    name: "T-MAX 400",
    iso: 400,
    type: "bw",
    process: "bw",
    aliases: ["t-max 400", "tmax 400", "kodak t-max 400", "kodak tmax 400", "tmax400"],
  },
  {
    id: "ilford-hp5-400",
    brand: "Ilford",
    name: "HP5 Plus",
    iso: 400,
    type: "bw",
    process: "bw",
    aliases: ["hp5", "hp5+", "hp5 plus", "ilford hp5", "ilford hp5 plus"],
  },
  {
    id: "ilford-delta-400",
    brand: "Ilford",
    name: "Delta 400",
    iso: 400,
    type: "bw",
    process: "bw",
    aliases: ["delta 400", "ilford delta 400", "ilforddelta400"],
  },
  {
    id: "kentmere-pan-400",
    brand: "Kentmere",
    name: "PAN 400",
    iso: 400,
    type: "bw",
    process: "bw",
    // No bare "kentmere pan" alias: it matched Kentmere Pan 100 as well, so PAN 100
    // listings were being priced as PAN 400 at four stores. Every alias must pin the ISO.
    aliases: ["kentmere pan 400", "kentmere 400", "kentmere pan400", "pan 400 kentmere"],
  },

  // --- Phase 1 additions (stocked at all three surveyed Shopify stores) ---

  {
    id: "fujifilm-200",
    brand: "Fujifilm",
    name: "Fujicolor 200",
    iso: 200,
    type: "color",
    process: "c41",
    // "fujifilm 200" alone is too loose — it would match any Fujifilm product whose
    // title happens to contain 200. Every alias pins a Fuji colour-film word.
    // "couleur" covers the French-language listings at Sténopé Lab.
    aliases: [
      "fujicolor 200",
      "fujifilm color 200",
      "fujifilm colour 200",
      "fujifilm couleur 200",
      "fujifilm 200 color",
      "fuji c200",
    ],
  },
  {
    id: "fujifilm-400",
    brand: "Fujifilm",
    name: "Fujicolor 400",
    iso: 400,
    type: "color",
    process: "c41",
    aliases: [
      "fujicolor 400",
      "fujifilm color 400",
      "fujifilm colour 400",
      "fujifilm couleur 400",
      "fujifilm 400 color",
    ],
  },
  {
    id: "harman-phoenix-200",
    brand: "Harman",
    name: "Phoenix 200",
    iso: 200,
    type: "color",
    process: "c41",
    aliases: ["harman phoenix 200", "phoenix 200", "harman phoenix ii", "phoenix ii"],
  },
  {
    id: "kodak-ektachrome-e100",
    brand: "Kodak",
    name: "Ektachrome E100",
    iso: 100,
    type: "color",
    process: "e6",
    // No bare "kodak ektachrome": it also matched Super 8 Ektachrome 100D.
    aliases: ["ektachrome e100", "ektachrome 100", "ektachrome e6"],
  },
  {
    id: "fujifilm-velvia-100",
    brand: "Fujifilm",
    name: "Velvia 100",
    iso: 100,
    type: "color",
    process: "e6",
    aliases: ["velvia 100", "fujichrome velvia 100", "fujifilm velvia 100"],
  },
  {
    id: "cinestill-800t",
    brand: "CineStill",
    name: "800T",
    iso: 800,
    type: "color",
    process: "c41",
    aliases: ["cinestill 800t", "cinestill 800 tungsten", "800tungsten", "cinestill 800"],
    // CineStill is sold only as 36 exposures.
    defaultExposures: 36,
  },
  {
    id: "cinestill-400d",
    brand: "CineStill",
    name: "400D",
    iso: 400,
    type: "color",
    process: "c41",
    aliases: ["cinestill 400d", "400dynamic", "cinestill 400 dynamic", "cinestill 400"],
    // CineStill is sold only as 36 exposures.
    defaultExposures: 36,
  },
  {
    id: "cinestill-50d",
    brand: "CineStill",
    name: "50D",
    iso: 50,
    type: "color",
    process: "c41",
    aliases: ["cinestill 50d", "50daylight", "cinestill 50 daylight", "cinestill 50"],
    // CineStill is sold only as 36 exposures.
    defaultExposures: 36,
  },
  {
    id: "ilford-fp4-125",
    brand: "Ilford",
    name: "FP4 Plus",
    iso: 125,
    type: "bw",
    process: "bw",
    aliases: ["ilford fp4", "fp4 plus", "fp4+", "fp4"],
  },
  {
    id: "ilford-delta-100",
    brand: "Ilford",
    name: "Delta 100",
    iso: 100,
    type: "bw",
    process: "bw",
    aliases: ["ilford delta 100", "delta 100"],
  },
  {
    id: "ilford-delta-3200",
    brand: "Ilford",
    name: "Delta 3200",
    iso: 3200,
    type: "bw",
    process: "bw",
    aliases: ["ilford delta 3200", "delta 3200"],
  },
  {
    id: "ilford-xp2-400",
    brand: "Ilford",
    name: "XP2 Super",
    iso: 400,
    type: "bw",
    // C-41 process black and white.
    process: "c41",
    aliases: ["ilford xp2", "xp2 super", "xp2"],
  },
  {
    id: "kodak-t-max-p3200",
    brand: "Kodak",
    name: "T-MAX P3200",
    iso: 3200,
    type: "bw",
    process: "bw",
    aliases: ["t-max p3200", "tmax p3200", "kodak t-max 3200", "kodak tmax 3200", "t-max 3200"],
  },

  // --- Phase 2 additions (second tier: stocked at two of three surveyed stores) ---

  {
    id: "kentmere-pan-100",
    brand: "Kentmere",
    name: "PAN 100",
    iso: 100,
    type: "bw",
    process: "bw",
    aliases: ["kentmere pan 100", "kentmere 100"],
  },
  {
    id: "kentmere-pan-200",
    brand: "Kentmere",
    name: "PAN 200",
    iso: 200,
    type: "bw",
    process: "bw",
    aliases: ["kentmere pan 200", "kentmere 200"],
  },
  {
    id: "fujifilm-provia-100f",
    brand: "Fujifilm",
    name: "Provia 100F",
    iso: 100,
    type: "color",
    process: "e6",
    aliases: ["provia"],
  },
  {
    id: "fujifilm-velvia-50",
    brand: "Fujifilm",
    name: "Velvia 50",
    iso: 50,
    type: "color",
    process: "e6",
    aliases: ["velvia 50"],
  },
  {
    id: "fujifilm-acros-100",
    brand: "Fujifilm",
    name: "Neopan 100 Acros II",
    iso: 100,
    type: "bw",
    process: "bw",
    // Stores write it "Acros 100 II" and "Acros 100 ll" (lowercase L), so match on
    // the distinctive word alone.
    aliases: ["acros"],
  },
  {
    id: "harman-red-125",
    brand: "Harman",
    name: "RED 125",
    iso: 125,
    type: "color",
    process: "c41",
    // One store writes the speed as "125iso", which no ISO token can match on a word
    // boundary, so "harman red" carries the match. It is specific enough.
    aliases: ["harman red", "red 125 redscale"],
  },
  {
    id: "kodak-pro-image-100",
    brand: "Kodak",
    name: "Pro Image 100",
    iso: 100,
    type: "color",
    process: "c41",
    aliases: ["pro image 100", "kodak pro image"],
  },
  {
    id: "kodak-kodacolor-100",
    brand: "Kodak",
    name: "Kodacolor 100",
    iso: 100,
    type: "color",
    process: "c41",
    // Popho spells it "Kodakcolor".
    aliases: ["kodacolor 100", "kodakcolor 100"],
  },
  {
    id: "kodak-kodacolor-200",
    brand: "Kodak",
    name: "Kodacolor 200",
    iso: 200,
    type: "color",
    process: "c41",
    aliases: ["kodacolor 200", "kodakcolor 200"],
  },
  {
    id: "fomapan-100",
    brand: "Foma",
    name: "Fomapan 100",
    iso: 100,
    type: "bw",
    process: "bw",
    // Covers the Classic and Retro lines; "Foma Ortho 400" is excluded because it
    // does not contain "fomapan".
    aliases: ["fomapan 100"],
  },
  {
    id: "fomapan-200",
    brand: "Foma",
    name: "Fomapan 200",
    iso: 200,
    type: "bw",
    process: "bw",
    aliases: ["fomapan 200"],
  },
  {
    id: "fomapan-400",
    brand: "Foma",
    name: "Fomapan 400",
    iso: 400,
    type: "bw",
    process: "bw",
    aliases: ["fomapan 400"],
  },
  {
    id: "lomography-cn-400",
    brand: "Lomography",
    name: "Color Negative 400",
    iso: 400,
    type: "color",
    process: "c41",
    aliases: ["lomography color negative 400"],
  },
  {
    id: "lomography-cn-800",
    brand: "Lomography",
    name: "Color Negative 800",
    iso: 800,
    type: "color",
    process: "c41",
    aliases: ["lomography color negative 800"],
  },
  {
    id: "lomochrome-metropolis",
    brand: "Lomography",
    name: "LomoChrome Metropolis",
    // Rated ISO 100-400.
    iso: null,
    type: "color",
    process: "c41",
    aliases: ["lomochrome metropolis"],
  },
  {
    id: "cinestill-bwxx",
    brand: "CineStill",
    name: "BwXX",
    iso: 250,
    type: "bw",
    process: "bw",
    // No bare "double-x": Flic Film sells its own Kodak Double-X respool.
    aliases: ["bwxx", "cinestill double-x", "cinestill double x"],
    // CineStill is sold only as 36 exposures.
    defaultExposures: 36,
  },
  {
    id: "flic-aurora-400",
    brand: "Flic Film",
    name: "Aurora 400",
    iso: 400,
    type: "color",
    process: "c41",
    // The ISO is load-bearing: one store sells "Aurora" branded umbrellas and
    // reflectors, which a bare "aurora" alias would match.
    aliases: ["aurora 400"],
  },
  {
    id: "flic-elektra-100",
    brand: "Flic Film",
    name: "Elektra 100",
    iso: 100,
    type: "color",
    process: "c41",
    aliases: ["elektra 100"],
  },

  {
    id: "flic-fusion-200",
    brand: "Flic Film",
    name: "Fusion 200",
    iso: 200,
    type: "color",
    process: "c41",
    // Graination lists it as bare "Fusion 200", so the brand cannot be required.
    // "fusion" is safe despite the many "Diffusion" products these stores sell:
    // word tokens match on a boundary, and "fusion" does not start one inside
    // "diffusion". The ISO is pinned regardless.
    aliases: ["fusion 200", "flic film fusion 200"],
  },

  {
    id: "lomography-analog-trio",
    brand: "Lomography",
    // A bundle of three different LomoChrome stocks, not three rolls of one film, so
    // it is tracked as its own product. The contents change over time — the current
    // pack is Metropolis / Purple / SunKissed, an earlier one had Turquoise — so the
    // name deliberately doesn't list them.
    name: "Analog Trio (3 rolls)",
    iso: null,
    type: "color",
    process: "c41",
    defaultPackSize: 3,
    aliases: ["lomography analog trio", "analog trio"],
  },

  // Candido: stocked only at Beau Photo, unblocked by its bulk adapter. C-41
  // respools of Kodak Vision3 with the remjet removed (200 <- 200T, 400 <- 250D,
  // 800 <- 500T).
  {
    id: "candido-200",
    brand: "Candido",
    name: "200",
    iso: 200,
    type: "color",
    process: "c41",
    aliases: ["candido 200"],
  },
  {
    id: "candido-400",
    brand: "Candido",
    name: "400",
    iso: 400,
    type: "color",
    process: "c41",
    aliases: ["candido 400"],
  },
  {
    id: "candido-800",
    brand: "Candido",
    name: "800",
    iso: 800,
    type: "color",
    process: "c41",
    aliases: ["candido 800"],
  },

  // --- Extended tier: stocked but not headline films. Found via `npm run discover`.
  // Skipped by the browser-driven stores; covered by the seven bulk stores.

  {
    id: "rollei-rpx-25",
    brand: "Rollei",
    name: "RPX 25",
    iso: 25,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["rollei rpx 25", "rpx 25"],
  },
  {
    id: "rollei-rpx-100",
    brand: "Rollei",
    name: "RPX 100",
    iso: 100,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["rollei rpx 100", "rpx 100"],
  },
  {
    id: "rollei-rpx-400",
    brand: "Rollei",
    name: "RPX 400",
    iso: 400,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["rollei rpx 400", "rpx 400"],
  },
  {
    id: "rollei-retro-80s",
    brand: "Rollei",
    name: "Retro 80S",
    iso: 80,
    type: "bw",
    process: "bw",
    tier: "extended",
    // "80s" carries the S, so it is a word token rather than an ISO.
    aliases: ["rollei retro 80s", "retro 80s"],
  },
  {
    id: "rollei-retro-400s",
    brand: "Rollei",
    name: "Retro 400S",
    iso: 400,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["rollei retro 400s", "retro 400s"],
  },
  {
    id: "rollei-superpan-200",
    brand: "Rollei",
    name: "Superpan 200",
    iso: 200,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["superpan 200", "rollei superpan"],
  },
  {
    id: "rollei-infrared-400",
    brand: "Rollei",
    name: "Infrared 400",
    iso: 400,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["rollei infrared"],
  },
  {
    id: "adox-chs-100",
    brand: "Adox",
    name: "CHS 100 II",
    iso: 100,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["adox chs", "chs 100"],
  },
  {
    id: "adox-hr-50",
    brand: "Adox",
    name: "HR-50",
    iso: 50,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["adox hr-50", "adox hr50"],
  },
  {
    id: "adox-scala-50",
    brand: "Adox",
    name: "Scala 50",
    iso: 50,
    type: "bw",
    // Black and white reversal.
    process: "bw",
    tier: "extended",
    // Beau Photo drops the brand, listing it as "Scala 50 …".
    aliases: ["adox scala", "scala 50"],
  },
  {
    id: "agfaphoto-apx-100",
    brand: "AgfaPhoto",
    name: "APX 100",
    iso: 100,
    type: "bw",
    process: "bw",
    tier: "extended",
    // One store spells the brand "Afga", so the alias leans on APX.
    aliases: ["apx 100"],
  },
  {
    id: "agfaphoto-apx-400",
    brand: "AgfaPhoto",
    name: "APX 400",
    iso: 400,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["apx 400"],
  },
  {
    id: "ferrania-p30",
    brand: "Ferrania",
    name: "P30",
    iso: 80,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["ferrania p30"],
  },
  {
    id: "ferrania-p33",
    brand: "Ferrania",
    name: "P33",
    iso: 160,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["ferrania p33"],
  },
  {
    id: "ferrania-orto-50",
    brand: "Ferrania",
    name: "Orto 50",
    iso: 50,
    type: "bw",
    process: "bw",
    tier: "extended",
    // Spelled both "Orto" and "Ortho"; one listing gives no ISO at all.
    aliases: ["ferrania orto", "ferrania ortho"],
  },
  {
    id: "ultrafine-xtreme-100",
    brand: "Ultrafine",
    name: "Xtreme 100",
    iso: 100,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["ultrafine xtreme 100"],
  },
  {
    id: "ultrafine-xtreme-400",
    brand: "Ultrafine",
    name: "Xtreme 400",
    iso: 400,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["ultrafine xtreme 400"],
  },
  {
    id: "washi-f-100",
    brand: "Film Washi",
    name: "F 100",
    iso: 100,
    type: "bw",
    process: "bw",
    tier: "extended",
    // The letter is a single character, which the matcher skips, so the ISO
    // separates F from Z rather than the name.
    aliases: ["washi 100"],
  },
  {
    id: "washi-z-400",
    brand: "Film Washi",
    name: "Z 400",
    iso: 400,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["washi 400"],
  },

  // --- Extended tier, batch 2 (from `npm run discover`) ---

  {
    id: "flic-ultrapan-100",
    brand: "Flic Film",
    name: "Ultrapan 100",
    iso: 100,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["ultrapan 100"],
  },
  {
    id: "flic-ultrapan-200",
    brand: "Flic Film",
    name: "Ultrapan 200",
    iso: 200,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["ultrapan 200"],
  },
  {
    id: "flic-ultrapan-400",
    brand: "Flic Film",
    name: "Ultrapan 400",
    iso: 400,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["ultrapan 400"],
  },
  {
    id: "flic-cine-50d",
    brand: "Flic Film",
    name: "Cine Colour 50D",
    iso: 50,
    type: "color",
    process: "c41",
    tier: "extended",
    // Flic sells its Vision3 respools under both names, so one film carries both.
    aliases: ["cine colour 50d", "cine color 50d", "vision3 50d"],
  },
  {
    id: "flic-cine-200t",
    brand: "Flic Film",
    name: "Cine Colour 200T",
    iso: 200,
    type: "color",
    process: "c41",
    tier: "extended",
    aliases: ["cine colour 200t", "cine color 200t", "vision3 200t"],
  },
  {
    id: "flic-cine-250d",
    brand: "Flic Film",
    name: "Cine Colour 250D",
    iso: 250,
    type: "color",
    process: "c41",
    tier: "extended",
    aliases: ["cine colour 250d", "cine color 250d", "vision3 250d"],
  },
  {
    id: "flic-cine-500t",
    brand: "Flic Film",
    name: "Cine Colour 500T",
    iso: 500,
    type: "color",
    process: "c41",
    tier: "extended",
    aliases: ["cine colour 500t", "cine color 500t", "vision3 500t"],
  },
  {
    id: "flic-aurora-800",
    brand: "Flic Film",
    name: "Aurora 800",
    iso: 800,
    type: "color",
    process: "c41",
    tier: "extended",
    aliases: ["aurora 800"],
  },
  {
    id: "flic-apollo-400",
    brand: "Flic Film",
    name: "Apollo 400",
    iso: 400,
    type: "color",
    process: "c41",
    tier: "extended",
    // Also sold as an 18-exposure roll branded Apollo 18.
    aliases: ["apollo 400", "apollo 18"],
  },
  {
    id: "flic-double-x",
    brand: "Flic Film",
    name: "Double-X 250",
    iso: 250,
    type: "bw",
    process: "bw",
    tier: "extended",
    // Kodak Double-X respool. CineStill sells its own as BwXX, so the brand is required here.
    aliases: ["flic film double-x", "flic film double x", "xx-250"],
  },
  {
    id: "flic-wolfen-100",
    brand: "Flic Film",
    name: "Wolfen 100",
    iso: 100,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["flic film wolfen", "wolfen 100"],
  },
  {
    id: "street-candy-mtn-100",
    brand: "Street Candy",
    name: "MTN 100",
    iso: 100,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["street candy mtn 100"],
  },
  {
    id: "street-candy-mtn-400",
    brand: "Street Candy",
    name: "MTN 400",
    iso: 400,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["street candy mtn 400"],
  },
  {
    id: "street-candy-savvy-400",
    brand: "Street Candy",
    name: "Street Savvy 400",
    iso: 400,
    type: "color",
    process: "c41",
    tier: "extended",
    aliases: ["street savvy"],
  },
  {
    id: "ilford-sfx-200",
    brand: "Ilford",
    name: "SFX 200",
    iso: 200,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["ilford sfx", "sfx 200"],
  },
  {
    id: "ilford-pan-f-50",
    brand: "Ilford",
    name: "Pan F Plus 50",
    iso: 50,
    type: "bw",
    process: "bw",
    tier: "extended",
    // The F is a single character the matcher skips, so match on panf or pan + plus.
    aliases: ["panf", "pan f plus"],
  },
  {
    id: "ilford-ortho-plus-80",
    brand: "Ilford",
    name: "Ortho Plus 80",
    iso: 80,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["ortho plus"],
  },
  {
    id: "harman-switch-azure",
    brand: "Harman",
    name: "Switch Azure 125",
    iso: 125,
    type: "color",
    process: "c41",
    tier: "extended",
    aliases: ["switch azure"],
  },
  {
    id: "foma-ortho-400",
    brand: "Foma",
    name: "Ortho 400",
    iso: 400,
    type: "bw",
    process: "bw",
    tier: "extended",
    // foma does not match inside fomapan on a word boundary.
    aliases: ["foma ortho"],
  },
  {
    id: "lucky-shd-100",
    brand: "Lucky",
    name: "SHD 100",
    iso: 100,
    type: "bw",
    process: "bw",
    tier: "extended",
    // One store writes the speed as 100iso, which no ISO token can match on a boundary.
    aliases: ["shd100", "shd 100iso"],
  },
  {
    id: "lucky-shd-400",
    brand: "Lucky",
    name: "SHD 400",
    iso: 400,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["shd400", "shd 400iso"],
  },
  {
    id: "reflx-100",
    brand: "Reflx Lab",
    name: "100",
    iso: 100,
    type: "color",
    process: "c41",
    tier: "extended",
    // 100R is a separate product; the word boundary keeps it out.
    aliases: ["reflx lab 100"],
  },
  {
    id: "reflx-200t",
    brand: "Reflx Lab",
    name: "200T",
    iso: 200,
    type: "color",
    process: "c41",
    tier: "extended",
    aliases: ["reflx lab 200t", "reflx 200 tungsten"],
  },
  {
    id: "reflx-250d",
    brand: "Reflx Lab",
    name: "250D",
    iso: 250,
    type: "color",
    process: "c41",
    tier: "extended",
    aliases: ["reflx lab 250d"],
  },
  {
    id: "reflx-400",
    brand: "Reflx Lab",
    name: "400",
    iso: 400,
    type: "color",
    process: "c41",
    tier: "extended",
    aliases: ["reflx lab 400"],
  },
  {
    id: "reflx-500t",
    brand: "Reflx Lab",
    name: "500T",
    iso: 500,
    type: "color",
    process: "c41",
    tier: "extended",
    aliases: ["reflx lab 500t"],
  },
  {
    id: "reflx-800",
    brand: "Reflx Lab",
    name: "800",
    iso: 800,
    type: "color",
    process: "c41",
    tier: "extended",
    aliases: ["reflx lab 800"],
  },
  {
    id: "lomochrome-classicolor-200",
    brand: "Lomography",
    name: "LomoChrome Classicolor 200",
    iso: 200,
    type: "color",
    process: "c41",
    tier: "extended",
    aliases: ["lomochrome classicolor"],
  },
  {
    id: "lomochrome-color92-400",
    brand: "Lomography",
    name: "LomoChrome Color 92",
    iso: 400,
    type: "color",
    process: "c41",
    tier: "extended",
    aliases: ["lomochrome color 92", "color 92"],
  },
  {
    id: "lomochrome-purple",
    brand: "Lomography",
    name: "LomoChrome Purple",
    iso: null,
    type: "color",
    process: "c41",
    tier: "extended",
    // Rated ISO 100-400.
    aliases: ["lomochrome purple"],
  },
  {
    id: "lomography-turquoise",
    brand: "Lomography",
    name: "Turquoise",
    iso: null,
    type: "color",
    process: "c41",
    tier: "extended",
    // One store misspells the brand as Lomograhpy.
    aliases: ["lomography turquoise", "lomograhpy turquoise"],
  },
  {
    id: "lomography-redscale-xr",
    brand: "Lomography",
    name: "Redscale XR",
    iso: null,
    type: "color",
    process: "c41",
    tier: "extended",
    aliases: ["lomography redscale"],
  },
  {
    id: "lomography-cn-100",
    brand: "Lomography",
    name: "Color Negative 100",
    iso: 100,
    type: "color",
    process: "c41",
    tier: "extended",
    aliases: ["lomography color negative 100"],
  },
  {
    id: "lomography-earl-grey-100",
    brand: "Lomography",
    name: "Earl Grey 100",
    iso: 100,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["earl grey"],
  },
  {
    id: "adox-cms-20",
    brand: "Adox",
    name: "CMS 20 II",
    iso: 20,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["adox cms", "cms 20"],
  },
  {
    id: "shanghai-gp3-400",
    brand: "Shanghai",
    name: "GP3 400",
    iso: 400,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["shanghai gp3", "gp3 400"],
  },
  {
    id: "jch-streetpan-400",
    brand: "JCH",
    name: "StreetPan 400",
    iso: 400,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["streetpan"],
  },
  {
    id: "revolog-echo",
    brand: "Revolog",
    name: "Echo",
    iso: 100,
    type: "color",
    process: "c41",
    tier: "extended",
    aliases: ["revolog echo"],
  },
  {
    id: "revolog-kolor",
    brand: "Revolog",
    name: "Kolor",
    iso: 200,
    type: "color",
    process: "c41",
    tier: "extended",
    aliases: ["revolog kolor"],
  },
  {
    id: "revolog-kosmos",
    brand: "Revolog",
    name: "Kosmos",
    iso: 200,
    type: "color",
    process: "c41",
    tier: "extended",
    aliases: ["revolog kosmos"],
  },
  {
    id: "retocolor-prism-200",
    brand: "Reto",
    name: "Retocolor Prism 200",
    iso: 200,
    type: "color",
    process: "c41",
    tier: "extended",
    aliases: ["retocolor prism 200"],
  },
  {
    id: "retocolor-prism-400",
    brand: "Reto",
    name: "Retocolor Prism 400",
    iso: 400,
    type: "color",
    process: "c41",
    tier: "extended",
    aliases: ["retocolor prism 400"],
  },
  {
    id: "dubblefilm-bubblegum-400",
    brand: "DubbleFilm",
    name: "Bubblegum 400",
    iso: 400,
    type: "color",
    process: "c41",
    tier: "extended",
    aliases: ["bubblegum 400"],
  },
  {
    id: "orwo-wolfen-np100",
    brand: "ORWO",
    name: "Wolfen NP100",
    iso: 100,
    type: "bw",
    process: "bw",
    tier: "extended",
    aliases: ["wolfen np100", "orwo np100"],
  },

  // --- Instant film (Polaroid) --------------------------------------------
  //
  // Sold by camera compatibility, not by speed: a 600 pack carries the battery that
  // powers the camera, so vintage 600 bodies can only shoot 600, while i-Type bodies
  // shoot both. That is the axis a buyer actually chooses on, so it is the name.
  //
  // ORDER MATTERS. Black & white comes before colour in each family because the
  // colour seeds carry a "white frame" alias for Beau Photo's
  // "Polaroid Originals 600 White Frame", which names the border rather than the
  // emulsion. `films.find()` takes the first match in this array, so a future
  // "Polaroid Originals 600 B&W White Frame" resolves to black & white rather than
  // being mis-assigned to colour. Covered by a test.
  {
    id: "polaroid-600-bw",
    brand: "Polaroid",
    name: "600 Black & White",
    iso: 640,
    type: "bw",
    process: null,
    format: "instant",
    defaultExposures: 8,
    aliases: ["polaroid 600 black white", "polaroid 600 b&w"],
  },
  {
    id: "polaroid-600-color",
    brand: "Polaroid",
    name: "600 Colour",
    iso: 640,
    type: "color",
    process: null,
    format: "instant",
    defaultExposures: 8,
    aliases: [
      "polaroid 600 color",
      "polaroid 600 colour",
      "polaroid originals 600 white frame",
    ],
  },
  {
    id: "polaroid-sx70-bw",
    brand: "Polaroid",
    name: "SX-70 Black & White",
    iso: 160,
    type: "bw",
    process: null,
    format: "instant",
    defaultExposures: 8,
    aliases: ["polaroid sx-70 black white", "polaroid sx70 black white", "polaroid sx-70 b&w"],
  },
  {
    id: "polaroid-sx70-color",
    brand: "Polaroid",
    name: "SX-70 Colour",
    iso: 160,
    type: "color",
    process: null,
    format: "instant",
    defaultExposures: 8,
    aliases: [
      "polaroid sx-70 color",
      "polaroid sx-70 colour",
      "polaroid sx70 color",
      "polaroid sx70 colour",
    ],
  },
  // Studio Argentique is the only tracked store carrying i-Type, and every pack of it
  // was out of stock when this was added — so the page will often show it unstocked
  // without that being a fault. Aden lists an i-Type *camera* but no i-Type film.
  {
    id: "polaroid-itype-bw",
    brand: "Polaroid",
    name: "i-Type Black & White",
    iso: 640,
    type: "bw",
    process: null,
    format: "instant",
    defaultExposures: 8,
    aliases: ["polaroid i-type black white", "polaroid i-type b&w", "polaroid itype b&w"],
  },
  {
    id: "polaroid-itype-color",
    brand: "Polaroid",
    name: "i-Type Colour",
    iso: 640,
    type: "color",
    process: null,
    format: "instant",
    defaultExposures: 8,
    aliases: ["polaroid i-type color", "polaroid i-type colour", "polaroid itype color"],
  },
];
